version: 2
log-file: /tmp/efm.log
log-level: 1
root-markers:
  - .git/

tools:
  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    format-stdin: true
    root-markers:
      - .git/

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  prettier: &prettier
    format-command: './node_modules/.bin/prettier'

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

languages:
  javascript:
    - <<: *eslint
    - <<: *prettier

  javascriptreact:
    - <<: *eslint
    - <<: *prettier

  javascript.jsx:
    - <<: *eslint
    - <<: *prettier

  lua:
    - <<: *lua-lua-format

  python:
    - <<: *python-black

  typescript:
    - <<: *eslint
    - <<: *prettier

  typescriptreact:
    - <<: *eslint
    - <<: *prettier

  typescript.jsx:
    - <<: *eslint
    - <<: *prettier
