version: 2
log-file: /tmp/efm.log
log-level: 1
root-markers:
  - .git/

tools:
  eslint: &eslint
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    format-stdin: true

  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
      - '%f:%l:%c %m'
      - '%f: %l: %m'

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  markdown-pandoc: &markdown-pandoc
    format-command: 'pandoc -f markdown -t gfm+smart --tab-stop=2 --wrap=preserve'
    format-stdin: true

  prettier: &prettier
    # Important that global version used for prettier is aligned
    # with the version specified in the given local project
    format-command: 'prettier --stdin-filepath ${INPUT}'
    format-stdin: true

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  # sh-shellcheck: &sh-shellcheck
  #   lint-command: 'shellcheck -f gcc -x'
  #   lint-source: 'shellcheck'
  #   lint-formats:
  #     - '%f:%l:%c: %trror: %m'
  #     - '%f:%l:%c: %tarning: %m'
  #     - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn -i 2'
    format-stdin: true

  solhint: &solhint
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-command: 'solhint --formatter unix stdin'
    lint-formats:
      - '%*[ ]%l:%c%*[ ]%trror%*[ ]%m'
      - '%*[ ]%l:%c%*[ ]%tarning%*[ ]%m'
      - '%f:%l:%c: %m [%trror/%r]'
      - '%f:%l:%c: %m [%tarning/%r]'
    lint-source: 'solhint'

languages:
  javascript:
    - <<: *eslint
    - <<: *prettier

  javascriptreact:
    - <<: *eslint
    - <<: *prettier

  javascript.jsx:
    - <<: *eslint
    - <<: *prettier

  json:
    - <<: *eslint

  lua:
    - <<: *lua-lua-format

  markdown:
    - <<: *markdown-markdownlint
    - <<: *markdown-pandoc

  python:
    - <<: *python-black

  sh:
    # - <<: *sh-shellcheck
    - <<: *sh-shfmt

  solidity:
    # - <<: *prettier
    - <<: *solhint

  typescript:
    - <<: *eslint
    - <<: *prettier

  typescriptreact:
    - <<: *eslint
    - <<: *prettier

  typescript.tsx:
    - <<: *eslint
    - <<: *prettier
