# Remove vertical spacing
# between shell prompts
add_newline = false

# Keep prompt on
# the same line
[line_break]
disabled = true

# Disable the package module
# showing the package version
[package]
disabled = true

# Disable showing some
# language versions
[lua]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true

# Increase the default timeout
command_timeout = 1000
