[colors.bright]
black = "#545862"
blue = "#565c64"
cyan = "#be5046"
green = "#353b45"
magenta = "#b6bdca"
red = "#d19a66"
white = "#c8ccd4"
yellow = "#3e4451"

[colors.cursor]
cursor = "#abb2bf"
text = "#282c34"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = ".9"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[window]
decorations = "none"

[window.padding]
x = 5
y = 5
